version: '3.4'

services:
  sampleapi:
    image: ${DOCKER_REGISTRY-}sampleapi
    environment: 
        - ASPNETCORE_ENVIRONMENT=prod
    build:
      context: .
      dockerfile: SampleApi/Dockerfile
